### ISSUE TITLE
Impossible to unfollow from user

### ISSUE THREAD

**Issue by stuxjkee** [thenetworkhere/bugs#11]
### Bug Type

Functional

### Reproduction steps

1. Login
2. Go to any public profile (https://ton.place/travelplaces for example)
3. Click on his followers 
4. Follow any user (Click on "+") 
5. Go to his page 
https://www.awesomescreenshot.com/video/11150979?key=8727c679cb4106e18e994493e3904a1c

### Actual result

No "unfollow" button available

### Expected result

"unfollow" button should be available 

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: Windows
- Browser: Chrome
- Version 105.0.5195.125

**Comment by agoglev** [comment]
You should turn off adult mode and follow/unfollow button will appear in profile.
