### ISSUE TITLE
No SignUp available for unlogged users that came from referral link

### ISSUE THREAD

**Issue by stuxjkee** [thenetworkhere/bugs#13]
### Bug Type

UI

### Reproduction steps

1. Login
2. Go to any post from feed 
3. Copy link
4. Go to referral page 
5. Create referral link for post 
6. Open new incognito tab
7. Enter referral url 
8. Click on black space to close the post 
https://www.awesomescreenshot.com/video/11151208?key=6e407aecd6f5501b1cde369d5439fb8b

### Actual result

Only Sign-In functionality available

### Expected result

SignUp should be available as well 

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: Windows
- Browser: Chrome
- Version 105.0.5195.125

**Comment by agoglev** [comment]
Sign Up and Sign In is same things on our platform.
