### ISSUE TITLE
earnings from referral issue

### ISSUE THREAD

**Issue by stuxjkee** [thenetworkhere/bugs#14]
### Bug Type

Functional

### Reproduction steps

1. Login
2. Go to any post from feed
3. Copy link
4. Go to referral page
5. Create referral link for post 
6. Open new incognito tab 
7. Create new user 
8. Open referral link 
9. Go to main page 
10. Click on buy erotic subscription 
11. Click on pay with crypto 
12. Pay with ton via crypto bot
13. Go to main account (where referral link was created) 
14. Go to profile 
15.Click on earnings -> TON
https://www.awesomescreenshot.com/video/11151546?key=8b0b822a80317fc178a93cb3de083b1f

### Actual result

Notification from tonplacebot: 
One of your referrals has successfully activated their membership. You earned 0.4 TON.
But only 0.02914 ton came (displayed 0.03 TON)
No 4-8 euro came for referral :(

### Expected result

1. 0.02914 ton should be displayed instead of (0.03 TON) 
2. 0.4 TON should came according to notification from telegram bot
3. 8 euro should came as referral bonus

### Suggested Severity

Critical

### Device

Desktop 
- OS: Windows
- Browser: Chrome
- Version 105.0.5195.125

**Comment by agoglev** [comment]
Buying erotic subscription via cryptobot no longer available.
