### ISSUE TITLE
oAuth Error on first Sign Up with Telegram

### ISSUE THREAD

**Issue by axosky** [thenetworkhere/bugs#2]
### Bug Type

Functional

### Reproduction steps

Preconditions: Have Telegram account not registered in TonPlace before

1. Click on "Create account"
2. Enter phone and proceed
3. Approve login in telegram
4. Back to login pop-up
5. Click "Accept"

### Actual result

on Desktop: Error message about HASH error appears
on Phones: Server error appears

### Expected result

Successfully logged in with TG account

### Suggested Severity

High

### Device

Desktop
- OS: 12.2 (21D49)
- Browser: Chrome 
- Version: 105.0.5195.102

Smartphone:
- Device: iPhone 7
- OS: 15.3
- Browser: Safari
- Version: 15.3

### Additional Context

The second login is successfull

https://user-images.githubusercontent.com/101420012/190667955-67652f92-a444-4924-b1c6-9f458e123e70.mp4
https://user-images.githubusercontent.com/101420012/190668266-88f7f44e-9fa7-4cdd-be43-f35fe7b9a68f.mp4

**Comment by agoglev** [comment]
It's Telegram side error.
