### ISSUE TITLE
VM9244:59 GET https://api.ton.place/utm/detect 400

### ISSUE THREAD

**Issue by isopen** [thenetworkhere/bugs#21]
### Bug Type

Functional

### Reproduction steps

![Снимок экрана от 2022-09-19 02-34-40](https://user-images.githubusercontent.com/7373292/190925238-61aa7bf4-e940-40d2-93f7-10dbec40b4b9.png)
![Снимок экрана от 2022-09-19 02-35-39](https://user-images.githubusercontent.com/7373292/190925276-f9612db4-b802-4fb3-9825-23df2e66d3c3.png)

### Actual result

Route not working

### Expected result

The route is running or canceled as obsolete

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: Ubuntu 22
- Browser Google Chrome
- Version 105.0.5195.52

**Comment by agoglev** [comment]
It's by design.
