### ISSUE TITLE
Strange behavior of the comments loader

### ISSUE THREAD

**Issue by isopen** [thenetworkhere/bugs#23]
### Bug Type

UI

### Reproduction steps

[vokoscreenNG-2022-09-19_08-37-01.webm](https://user-images.githubusercontent.com/7373292/190937707-3aa598f3-ef51-42ef-b352-246bd350e0c3.webm)

### Actual result

Before displaying the loader, it already displays "Нет комментариев".

### Expected result

Show the loader when launching the comments modal window
If comments are found, then display them
If not found, then "Нет комментариев" (If 0, then it is better not to show the loader at all)

### Suggested Severity

Low

### Device

Desktop (please complete the following information):

OS: Ubuntu 22
Browser Google Chrome
Version 105.0.5195.52

**Comment by agoglev** [comment]
We always send requests to check new comments and user should know about this process.
