### ISSUE TITLE
Log out button is not available directly from homepage

### ISSUE THREAD

**Issue by ArteSK88** [thenetworkhere/bugs#26]
### Bug Type

UX

### Reproduction steps

Precondition:
1. Enter URL https://ton.place/
2. Sign up and log in.

Steps:
1. Click on 'More' at the left-side panel.
2. Scroll down and select 'Settings' at the lower section.

https://user-images.githubusercontent.com/108936297/191135335-f9a3aa07-8f6d-4f2e-8bf9-868e9d013548.mp4

![LogOut](https://user-images.githubusercontent.com/108936297/191135355-da576622-9cfa-403c-95ad-66f780681796.png)

### Actual result

To reveal 'Log out' button it requires to take path More/Settings

### Expected result

'Log out' button is available directly from homepage.

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: Windows 10 64-bit
- Browser: Chrome
- Version 105.0.5195.127

**Comment by agoglev** [comment]
Users use the feature once in few months. It's can't be on homepage.
