### ISSUE TITLE
Faild connect with telegramm/tonplacebot dont work

### ISSUE THREAD

**Issue by BelfegorVoodoo** [thenetworkhere/bugs#30]
### Bug Type

Functional

### Reproduction steps

1 Click connect with telegramm
2 Telegramm open tonplacebot

### Actual result

![photo_2022-09-25_08-24-09](https://user-images.githubusercontent.com/94609634/192129620-9eecd42a-9b9d-4e15-819d-21dd0b39948f.jpg)

### Expected result

Bot cant do any action (o contrer Ton.Place Help works good)

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):

### Additional Context

Bad graphics and no style at all
Also no sign that its XXX erotic/porn content before you visit it

**Comment by agoglev** [comment]
The bot created for authorization and sending notifications for users and shoudn't do any other actions.
