### ISSUE TITLE
Тhere is no "choose your style..." block and radio buttons

### ISSUE THREAD

**Issue by Yulia922** [thenetworkhere/bugs#4]
### Bug Type

UX

### Reproduction steps

1. Open https://ton.place/ on the English version on 2nd block

### Actual result

Тhere is no "choose your style..." block and radio buttons on the English version
![image](https://user-images.githubusercontent.com/93192129/190697821-274c5e43-8aff-45bb-863e-7483e37d90c6.png)
![image](https://user-images.githubusercontent.com/93192129/190697913-0c472576-e2f2-4075-a143-89cef419f112.png)

### Expected result

Should be "choose your style..." block and radio buttons on the English version

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS:  Windows
- Browser: chrome
- Version: 105.0.5195.126

**Comment by agoglev** [comment]
It's by design.
