### ISSUE TITLE
There is 400 error in /utm/detect on the feed page

### ISSUE THREAD

**Issue by Yulia922** [thenetworkhere/bugs#5]
### Bug Type

Functional

### Reproduction steps

1. Open the feed page

### Actual result

400 error in ttps://api.ton.place/utm/detect 
![image](https://user-images.githubusercontent.com/93192129/190700767-2158a97d-2db5-44e7-9bf4-6b53a846cdbd.png)
![image](https://user-images.githubusercontent.com/93192129/190700808-a90aa567-6cec-4315-8e6c-29bb7c08b5d2.png)

### Expected result

should be no error

### Suggested Severity

Medium

### Device

OS: Windows
Browser: chrome
Version: 105.0.5195.126

**Comment by agoglev** [comment]
It's by design.
