### ISSUE TITLE
There is a scroll up when switching the second switch

### ISSUE THREAD

**Issue by pinkx1** [thenetworkhere/bugs#8]
### Bug Type

Functional

### Reproduction steps

1. Open https://ton.place/
2. Click on "Модель 18+"
3. Click on "медиа создатель" below

### Actual result

Page scrolls up

https://user-images.githubusercontent.com/99640795/190843282-f255daf5-d428-441e-9a59-e8592a124b52.mp4

### Expected result

Scroll is not happening

### Suggested Severity

Low

### Device

- OS: MacOS Monterey 12.4 (21F79)
- Google Chrome
- 105.0.5195.102

**Comment by agoglev** [comment]
It's by design, because first part of the page changed.
